(() => {
  'use strict';
  const formLabels = { bm01: 'BM01 — Khí không ngưng tụ', bm02: 'BM02 — Nước ngưng', bm03: 'BM03 — Độ khô', bm04: 'BM04 — Quá nhiệt', bm05: 'BM05 — Tổng hợp đánh giá' };
  const formNotes = { bm01: 'Nhập 3 lần đo cho mỗi điểm. Dấu phẩy thập phân được máy chủ kiểm tra.', bm02: 'Nhập kết quả kiểm nghiệm theo từng điểm; nội độc tố có thể không áp dụng.', bm03: 'Thông tin thiết bị và 3 lần đo được chuyển sang máy chủ để tính độ khô.', bm04: 'T3 được đọc từ BM03 của đúng điểm và đúng lần đo.', bm05: 'Tổng hợp dựa trên kết quả máy chủ trả về; không thay cho phê duyệt.' };
  const trialFields = {
    bm01: [['vg', 'Vg', 'mL'], ['vc', 'Vc', 'mL']],
    bm03: [['me', 'Me', 'kg'], ['ms', 'Ms', 'kg'], ['mf', 'Mf', 'kg'], ['t1', 'T1', '°C'], ['t2', 'T2', '°C'], ['t3', 'T3', '°C']],
    bm04: [['te', 'Te', '°C'], ['to', 'To', '°C'], ['ts', 'Ts', '°C']]
  };
  const bm02Fields = [['appearance', 'Cảm quan', '', 'text'], ['conductivity', 'Độ dẫn điện', 'µS/cm', 'number'], ['toc', 'TOC', 'ppb', 'number'], ['microbial', 'Vi sinh', 'CFU/100 mL', 'number'], ['endotoxin', 'Nội độc tố', 'EU/mL', 'number'], ['sample_chem', 'Mã mẫu hóa lý', '', 'text'], ['sample_micro', 'Mã mẫu vi sinh', '', 'text'], ['sample_endo', 'Mã mẫu nội độc tố', '', 'text'], ['executor', 'Người thực hiện', '', 'text'], ['date', 'Ngày đo', '', 'date']];
  const metaFields = [['executed_by', 'Người thực hiện phần tổng hợp BM01–BM04', '', 'text'], ['execution_date', 'Ngày thực hiện BM01–BM04', '', 'date'], ['evaluated_by', 'Người đánh giá BM05', '', 'text'], ['reported_by', 'Người lập báo cáo', '', 'text'], ['report_date', 'Ngày lập báo cáo', '', 'date'], ['evaluation_date', 'Ngày đánh giá', '', 'date'], ['next_evaluation', 'Đánh giá kế tiếp', '', 'date'], ['remarks', 'Nhận xét', '', 'textarea'], ['deviation', 'Sai lệch', '', 'textarea']];
  const equipmentFields = [['balance_due', 'Hạn hiệu chuẩn cân', '', 'date'], ['balance_status', 'Tình trạng cân', '', 'text'], ['thermometer_due', 'Hạn hiệu chuẩn nhiệt kế', '', 'date'], ['thermometer_status', 'Tình trạng nhiệt kế', '', 'text']];
  const $ = (id) => document.getElementById(id);
  const entryQuery = new URLSearchParams(location.search);
  let requestedRecords = entryQuery.get('view') === 'records';
  const initialForm = Object.hasOwn(formLabels, entryQuery.get('form')) ? entryQuery.get('form') : 'bm01';
  const state = { config: null, active: initialForm, location: null, data: blankData(), result: null, recordId: null, version: null, session: null, dirty: false, loading: false, generation: 0, saveRequestId: null };
  function blankData() { return { meta: {}, equipment: {}, bm01: {}, bm02: {}, bm03: {}, bm04: {} }; }
  function locations() { return state.config?.locations || []; }
  function entryReady(ready) { ['draft-download','draft-open','record-load','record-save','evaluate','print','location-search'].forEach(id => $(id).disabled = !ready); document.querySelector('.action-bar').hidden = !ready; }
  function welcome() { entryReady(false); $('record-state').textContent = 'Chưa đăng nhập'; $('form-title').textContent = 'Hơi tinh khiết'; $('form-subtitle').textContent = 'Đăng nhập để chọn biểu mẫu, nhập số liệu và mở hồ sơ đã lưu.'; $('connection-text').textContent = 'Chưa đăng nhập'; $('connection-dot').className = 'dot'; $('formula-version').textContent = '—'; $('form-nav').replaceChildren(); $('form-body').replaceChildren(el('section', { className: 'entry-welcome' }, [el('p', { className: 'eyebrow', text: 'KHÔNG GIAN LÀM VIỆC' }), el('h2', { text: 'Bắt đầu nhập báo cáo' }), el('p', { text: 'Nhập số liệu theo biểu mẫu → tính và đánh giá → lưu hồ sơ → in theo form gốc.' }), el('button', { type: 'button', className: 'button primary', text: 'Đăng nhập để bắt đầu', onClick: () => $('auth-dialog').showModal() })])); }
  function configField(form, key, fallback) { return state.config?.forms?.find(item => item.id === form)?.fields?.find(item => item.key === key) || fallback; }
  function locationId() { return state.location || locations()[0]?.id || ''; }
  function safeText(value, max = 240) { return String(value ?? '').slice(0, max); }
  function el(tag, props = {}, children = []) { const node = document.createElement(tag); Object.entries(props).forEach(([key, value]) => { if (value === undefined || value === null) return; if (key === 'className') node.className = value; else if (key === 'text') node.textContent = safeText(value); else if (key.startsWith('on')) node.addEventListener(key.slice(2).toLowerCase(), value); else node.setAttribute(key, String(value)); }); children.forEach(child => node.append(child)); return node; }
  function field(key, label, unit = '', type = 'text', value = '', readOnly = false, options = null) {
    const wrapper = el('div', { className: 'field' }); const id = `input-${key}`;
    wrapper.append(el('label', { for: id, text: label }), unit ? el('span', { className: 'unit', text: ` (${unit})` }) : document.createTextNode(''));
    const input = type === 'textarea' ? el('textarea', { id, name: key, maxlength: '500' }) : type === 'select' ? el('select', { id, name: key }) : el('input', { id, name: key, type: type === 'number' ? 'text' : type, maxlength: type === 'text' ? '160' : '40', inputmode: type === 'number' ? 'decimal' : undefined });
    if (type === 'select') (options || []).forEach(option => input.append(el('option', { value: option.value, text: option.label })));
    input.setAttribute('aria-describedby', `${id}-error`); input.value = safeText(value, type === 'textarea' ? 500 : 160); if (readOnly) { input.readOnly = true; input.classList.add('readonly'); }
    if (!readOnly) input.addEventListener('input', () => { writePath(key, input.value); markDirty(); });
    wrapper.append(input, el('p', { className: 'field-error', id: `${id}-error` })); return wrapper;
  }
  function safeLocationKey(id) { return id.replaceAll('.', '__dot__'); }
  function pathKey(section, id, trial, key) { return `${section}.${safeLocationKey(id)}.${trial}.${key}`; }
  function writePath(path, value) { const parts = path.split('.'); if (parts.length > 2 && ['bm01', 'bm02', 'bm03', 'bm04'].includes(parts[0])) parts[1] = parts[1].replaceAll('__dot__', '.'); let obj = state.data; for (let i = 0; i < parts.length - 1; i++) obj = obj[parts[i]] ||= {}; obj[parts.at(-1)] = value; }
  function readPath(path) { return path.split('.').reduce((a, p) => a && a[p], state.data) || ''; }
  function markDirty() { state.generation += 1; state.saveRequestId = null; state.dirty = true; if (state.recordId) $('record-state').textContent = `Hồ sơ ${state.recordId} có thay đổi chưa lưu`; if (state.result) { state.result = null; $('draft-state').textContent = 'Dữ liệu đã đổi; hãy tính lại để xem kết quả mới.'; document.querySelectorAll('.result-box').forEach(box => { box.replaceChildren(el('strong', { text: 'Cần tính lại' }), el('span', { className: 'status incomplete', text: 'Kết quả cũ đã bị xóa' })); }); renderLocations(); } }
  function setMessage(text, kind = '') { const box = $('message'); box.textContent = text; box.className = `message ${kind}`; box.hidden = !text; }
  function renderNav() { const nav = $('form-nav'); nav.replaceChildren(); Object.entries(formLabels).forEach(([id, label]) => { const b = el('button', { type: 'button', className: 'nav-button', text: id.toUpperCase(), 'aria-current': state.active === id ? 'page' : 'false', onClick: () => { state.active = id; render(); } }); b.title = label; nav.append(b); }); }
  function statusText(status) { return ({ pass: 'Đạt', fail: 'Không đạt', incomplete: 'Chưa đủ dữ liệu', invalid: 'Dữ liệu không hợp lệ', not_applicable: 'Không áp dụng' })[status] || 'Chưa tính'; }
  function statusOfLocation(id) { return state.result?.forms?.[state.active]?.locations?.[id] || state.result?.forms?.[state.active]?.rows?.[id]?.status || 'incomplete'; }
  function renderLocations() { const list = $('location-list'); list.replaceChildren(); const query = $('location-search').value.trim().toLocaleLowerCase('vi'); const chosen = locationId(); const visible = locations().filter(x => `${x.id} ${x.name}`.toLocaleLowerCase('vi').includes(query)); $('location-count').textContent = `${visible.length}/${locations().length}`; visible.forEach(loc => { const status = statusOfLocation(loc.id); const b = el('button', { type: 'button', className: 'location-button', 'aria-current': loc.id === chosen ? 'true' : 'false', onClick: () => { state.location = loc.id; render(); } }); b.append(el('span', { className: `loc-status ${status}`, 'aria-hidden': 'true' }), el('span', { text: `${loc.id} — ${loc.name}` }), el('span', { className: 'sr-only', text: statusText(status) })); list.append(b); }); }
  function card(title, note, content) { return el('section', { className: 'card' }, [el('div', { className: 'card-head' }, [el('div', {}, [el('h2', { text: title }), el('p', { text: note })])]), el('div', { className: 'card-body' }, Array.isArray(content) ? content : [content])]); }
  function resultCell(result) { const status = result?.status || 'incomplete'; const values = result?.values || {}; const parts = []; if (values.result !== undefined) parts.push(`Kết quả: ${values.result}`); if (values.print_result !== undefined && values.print_result !== values.result) parts.push(`Trên form: ${values.print_result}`); ['latent', 'delta', 't3'].forEach(key => { if (values[key] !== undefined) parts.push(`${key === 'latent' ? 'L' : key === 'delta' ? 'ΔT' : 'T3'}: ${values[key]}`); }); return el('div', { className: 'result-box' }, [el('strong', { text: parts.join(' · ') || 'Chưa có kết quả' }), el('span', { className: `status ${status}`, text: statusText(status) })]); }
  function runTable(form) {
    const id = locationId();
    state.data[form][id] ||= [];
    while (state.data[form][id].length < 3) state.data[form][id].push({});
    const runs = state.data[form][id].map((run, index) => {
      const fields = trialFields[form].map(([key, label, unit]) => {
        const spec = configField(form, key, { label, unit, type: 'number' });
        return field(pathKey(form, id, index, key), spec.label, spec.unit || unit, spec.type || 'number', run[key], false, spec.options);
      });
      if (form === 'bm04') {
        const fromBm03 = state.data.bm03?.[id]?.[index]?.t3 || '';
        fields.push(field(`bm04.${safeLocationKey(id)}.${index}.t3-copy`, 'T3 từ BM03', '°C', 'number', fromBm03, true));
      }
      fields.push(field(pathKey(form, id, index, 'executor'), 'Người thực hiện', '', 'text', run.executor), field(pathKey(form, id, index, 'date'), 'Ngày đo', '', 'date', run.date));
      const result = state.result?.forms?.[form]?.rows?.[id]?.[index];
      return el('fieldset', { className: 'trial-group' }, [
        el('legend', { text: `Lần đo ${index + 1}` }),
        el('div', { className: 'trial-fields' }, fields),
        resultCell(result)
      ]);
    });
    return el('div', { className: 'trial-groups' }, runs);
  }
  function renderBm02() { const id = locationId(); const loc = locations().find(item => item.id === id); state.data.bm02[id] ||= {}; const data = state.data.bm02[id]; const fields = bm02Fields.filter(([key]) => loc?.endotoxin || !['endotoxin', 'sample_endo'].includes(key)).map(([key, label, unit, type]) => { const spec = configField('bm02', key, { label, unit, type }); return field(`bm02.${safeLocationKey(id)}.${key}`, spec.label, spec.unit || unit, spec.type || type, data[key], false, spec.options); }); if (!loc?.endotoxin) { delete data.endotoxin; delete data.sample_endo; fields.push(el('div', { className: 'field' }, [el('label', { text: 'Nội độc tố' }), el('p', { className: 'field-help', text: 'Không áp dụng tại điểm lấy mẫu này.' })])); } const result = state.result?.forms?.bm02?.rows?.[id]; return card('Kết quả tại điểm lấy mẫu', 'Để trống khi chưa có kết quả kiểm nghiệm.', [el('div', { className: 'field-grid' }, fields), el('div', { className: 'card-head' }, [el('div', {}, [el('h2', { text: 'Đánh giá từ máy chủ' }), el('p', { text: 'Không có kết luận mặc định khi dữ liệu còn trống.' })]), resultCell(result)])]); }
  function renderBm05() { const meta = metaFields.map(([key, label, unit, type]) => field(`meta.${key}`, label, unit, type, state.data.meta[key])); const overall = state.result?.overall; const status = typeof overall === 'string' ? overall : overall?.status || 'incomplete'; const rows = el('div', { className: 'records-list' }); ['bm01', 'bm02', 'bm03', 'bm04'].forEach(id => { const form = state.result?.forms?.[id]; const summary = form?.summary; rows.append(el('div', { className: 'record-item' }, [el('strong', { text: `${formLabels[id]} — ${statusText(form?.status || 'incomplete')}` }), el('span', { text: summary ? `${summary.pass} đạt · ${summary.fail} không đạt · ${summary.incomplete} chưa đủ / ${summary.total} điểm` : 'Chưa tính' })])); }); const summary = el('div', { className: 'result-box' }, [el('strong', { text: overall ? statusText(status) : 'Chưa có tổng hợp' }), el('span', { className: `status ${status}`, text: 'Tổng hợp do máy chủ trả về.' })]); return card('Thông tin báo cáo và tổng hợp', 'Phần phê duyệt chính thức không thuộc bản thử này.', [el('div', { className: 'meta-grid' }, meta), rows, el('div', { className: 'card-head' }, [el('div', {}, [el('h2', { text: 'Kết quả tổng hợp' }), el('p', { text: 'Tổng hợp từ bốn biểu mẫu.' })]), summary])]); }
  function renderEquipment() { return card('Thiết bị đo', 'Hạn hiệu chuẩn và tình trạng dụng cụ dùng cho BM03.', el('div', { className: 'field-grid' }, equipmentFields.map(([key, label, unit, type]) => field(`equipment.${key}`, label, unit, type, state.data.equipment[key])))); }
  function render() { renderNav(); renderLocations(); const loc = locations().find(x => x.id === locationId()); $('current-location').textContent = loc ? `${loc.id} — ${loc.name}` : '—'; $('form-title').textContent = formLabels[state.active]; $('form-subtitle').textContent = formNotes[state.active]; const body = $('form-body'); body.replaceChildren(); if (!loc && state.active !== 'bm05') { body.append(el('div', { className: 'empty', text: 'Chưa nhận được danh sách điểm từ máy chủ.' })); return; } if (state.active === 'bm02') body.append(renderBm02()); else if (state.active === 'bm05') body.append(renderBm05()); else { if (state.active === 'bm03') body.append(renderEquipment()); body.append(card(`Số liệu ${loc.id} — ${loc.name}`, formNotes[state.active], runTable(state.active))); } }
  function payload() { return JSON.parse(JSON.stringify(state.data)); }
  function clearErrors() { document.querySelectorAll('[aria-invalid="true"]').forEach(x => x.removeAttribute('aria-invalid')); $('error-summary').hidden = true; $('error-summary').replaceChildren(); document.querySelectorAll('.field-error').forEach(x => x.textContent = ''); }
  function applyErrors(result) { clearErrors(); const links = []; const current = result?.forms?.[state.active]?.rows?.[locationId()]; const rows = Array.isArray(current) ? current : current ? [current] : []; rows.forEach((row, run) => Object.entries(row?.errors || {}).forEach(([key, message]) => { const prefix = state.active === 'bm05' ? `meta.${key}` : state.active === 'bm02' ? `bm02.${safeLocationKey(locationId())}.${key}` : pathKey(state.active, locationId(), run, key); const input = document.querySelector(`[name="${CSS.escape(prefix)}"]`); if (input) { input.setAttribute('aria-invalid', 'true'); const error = $(`${input.id}-error`); if (error) error.textContent = safeText(message); links.push([input, message]); } })); if (links.length) { const box = $('error-summary'); box.append(el('h2', { text: 'Cần kiểm tra lại dữ liệu' })); const ul = el('ul'); links.forEach(([input, message]) => { const li = el('li'); li.append(el('a', { href: `#${input.id}`, text: message, onClick: () => input.focus() })); ul.append(li); }); box.append(ul); box.hidden = false; box.focus(); } }
  async function evaluate() { if (state.loading) return; state.loading = true; $('evaluate').disabled = true; const generation = state.generation; setMessage('Đang gửi số liệu để máy chủ tính và đánh giá…'); try { const result = await window.CPC1_API.evaluate(payload()); if (generation !== state.generation) { setMessage('Dữ liệu đã thay đổi trong khi tính; kết quả này không được áp dụng.', 'error'); return; } state.result = result; $('draft-state').textContent = 'Đã có kết quả máy chủ. Sửa bất kỳ ô nào sẽ yêu cầu tính lại.'; setMessage('Máy chủ đã trả kết quả. Hãy kiểm tra trước khi in bản nháp.'); render(); applyErrors(state.result); } catch (error) { setMessage(`Không thể tính: ${error.message} Dữ liệu vẫn ở trên trang.`, 'error'); } finally { state.loading = false; $('evaluate').disabled = false; } }
  async function printPdf() { if (state.loading) return; const popup = window.open('', '_blank'); if (popup) popup.opener = null; const session = state.session; state.loading = true; $('print').disabled = true; setMessage('Đang tạo PDF bản nháp…'); try { const blob = await window.CPC1_API.report(state.active, payload()); if (session !== state.session) { if (popup) popup.close(); return; } if (blob.type && !blob.type.includes('pdf')) throw new Error('Máy chủ không trả về tệp PDF.'); const url = URL.createObjectURL(blob); setTimeout(() => URL.revokeObjectURL(url), 60000); if (popup) { popup.location.href = url; setMessage('Đã mở PDF theo mẫu gốc. Khi in chọn Kích thước thực / 100% để giữ đúng khổ và cỡ chữ.'); } else { setMessage('Popup bị chặn; dùng liên kết tải PDF.'); $('message').append(document.createTextNode(' '), el('a', { href: url, download: 'CPC1-ban-nhap.pdf', text: 'Tải PDF bản nháp' })); } } catch (error) { if (popup) popup.close(); setMessage(`Không thể tạo PDF: ${error.message} Dữ liệu vẫn ở trên trang.`, 'error'); } finally { state.loading = false; $('print').disabled = false; } }
  function applyRecord(loaded) { if (!loaded?.data || typeof loaded.data !== 'object') throw new Error('Hồ sơ trả về không đúng cấu trúc.'); state.generation += 1; state.saveRequestId = null; state.data = loaded.data; state.result = loaded.evaluation || loaded.result || null; state.recordId = safeText(loaded.id, 120); state.version = loaded.version ?? null; state.dirty = false; clearErrors(); $('record-state').textContent = `Đã lưu Supabase · hồ sơ ${state.recordId} · phiên bản ${state.version}`; render(); }
  async function saveRecord() { if (!window.CPC1_API.capabilities?.persistence || state.loading) { setMessage('Dịch vụ hồ sơ chưa kết nối hoặc đang xử lý yêu cầu.', 'error'); return; } state.loading = true; $('record-save').disabled = true; const generation = state.generation; const data = state.data; const session = state.session; try { state.saveRequestId ||= crypto.randomUUID ? crypto.randomUUID() : `${Date.now()}-${Math.random()}`; const saved = await window.CPC1_API.save(payload(), { recordId: state.recordId, expectedVersion: state.version ?? 0, requestId: state.saveRequestId, title: 'Hơi tinh khiết — báo cáo nháp' }); if (data !== state.data || session !== state.session) return; if (generation !== state.generation) { state.recordId = safeText(saved?.id || state.recordId, 120); state.version = saved?.version ?? state.version; $('record-state').textContent = `Hồ sơ ${state.recordId} có thay đổi chưa lưu`; setMessage('Đã lưu phiên trước; các thay đổi mới hơn chưa được lưu.', 'error'); return; } state.saveRequestId = null; applyRecord(saved); setMessage('Đã lưu hồ sơ Supabase.'); } catch (error) { setMessage(`Không thể lưu hồ sơ: ${error.message} Dữ liệu đang nhập vẫn được giữ nguyên.`, 'error'); } finally { state.loading = false; $('record-save').disabled = false; } }
  async function loadRecord(id) { if (state.dirty && !window.confirm('Dữ liệu chưa lưu sẽ bị thay thế. Tiếp tục mở hồ sơ khác?')) return; const session = state.session; const generation = state.generation; try { const loaded = await window.CPC1_API.load(id); if (session !== state.session || generation !== state.generation) return; applyRecord(loaded); setMessage('Đã mở hồ sơ từ Supabase.'); } catch (error) { setMessage(`Không thể mở hồ sơ: ${error.message}`, 'error'); } }
  async function listRecords() { if (!window.CPC1_API.capabilities?.persistence) { setMessage('Đây là chế độ xem trước; dịch vụ hồ sơ chưa kết nối.', 'error'); return; } const dialog = $('records-dialog'); const list = $('records-list'); const session = state.session; list.replaceChildren(el('p', { text: 'Đang tải hồ sơ…' })); dialog.showModal(); try { const records = await window.CPC1_API.list(); if (session !== state.session) return; list.replaceChildren(); if (!Array.isArray(records) || !records.length) list.append(el('p', { text: 'Chưa có hồ sơ đã lưu.' })); else records.forEach(record => { const b = el('button', { type: 'button', className: 'record-item', onClick: () => { dialog.close(); loadRecord(record.id); } }); b.append(el('strong', { text: record.title || `Hồ sơ ${record.id}` }), el('span', { text: `${record.updated_at || record.created_at || ''} · phiên bản ${record.version ?? '—'}` })); list.append(b); }); } catch (error) { if (session === state.session) list.replaceChildren(el('p', { className: 'field-error', text: `Không tải được danh sách: ${error.message}` })); } }
  async function refreshSession() { state.session = await window.CPC1_API.getSession(); const signedIn = Boolean(state.session); $('auth-button').hidden = !window.CPC1_API.capabilities?.auth; $('auth-button').textContent = signedIn ? 'Đăng xuất' : 'Đăng nhập'; if (window.CPC1_API.capabilities?.auth && !signedIn) { welcome(); return false; } return true; }
  async function signIn(event) { event.preventDefault(); $('auth-error').textContent = ''; try { await window.CPC1_API.signIn($('auth-email').value, $('auth-password').value); $('auth-password').value = ''; $('auth-dialog').close(); if (await refreshSession()) { await loadConfig(); await openRequestedRecords(); } } catch (error) { $('auth-error').textContent = `Không thể đăng nhập: ${error.message}`; } }
  function downloadDraft() { const blob = new Blob([JSON.stringify({ version: 1, data: payload() }, null, 2)], { type: 'application/json' }); const a = el('a', { href: URL.createObjectURL(blob), download: 'cpc1-hoi-tinh-khiet-ban-nhap.json' }); document.body.append(a); a.click(); a.remove(); URL.revokeObjectURL(a.href); setMessage('Đã tải bản nháp về máy. Bản nháp không được lưu trên máy chủ.'); }
  function validDraft(candidate) { if (!candidate || typeof candidate !== 'object' || candidate.version !== 1 || !candidate.data || Object.getPrototypeOf(candidate.data) !== Object.prototype) return false; const data = candidate.data; const scalar = (value, max = 200) => typeof value === 'string' && value.length <= max && !/[\u0000-\u001f]/.test(value.replace(/[\n\t]/g, '')); const clean = object => Object.getPrototypeOf(object) === Object.prototype && !Object.keys(object).some(key => ['__proto__', 'prototype', 'constructor'].includes(key)); if (!['meta', 'equipment', 'bm01', 'bm02', 'bm03', 'bm04'].every(key => clean(data[key]))) return false; const locationsSet = new Set(locations().map(loc => loc.id)); if (Object.keys(data.meta).some(key => !metaFields.some(field => field[0] === key) || !scalar(data.meta[key], 500)) || Object.keys(data.equipment).some(key => !equipmentFields.some(field => field[0] === key) || !scalar(data.equipment[key]))) return false; for (const form of ['bm01', 'bm02', 'bm03', 'bm04']) for (const [id, value] of Object.entries(data[form])) { if (!locationsSet.has(id)) return false; const allowed = new Set(form === 'bm02' ? bm02Fields.map(field => field[0]) : [...trialFields[form].map(field => field[0]), 'executor', 'date']); const rows = form === 'bm02' ? [value] : value; if (!Array.isArray(rows) || rows.length > 3 || rows.some(row => !clean(row) || Object.entries(row).some(([key, item]) => !allowed.has(key) || !scalar(item, 500)))) return false; } return true; }
  function openDraft(file) { if (!file || file.size > 1024 * 1024) { setMessage('Chỉ mở bản nháp JSON nhỏ hơn 1 MB.', 'error'); return; } const reader = new FileReader(); reader.onload = () => { try { const candidate = JSON.parse(String(reader.result)); if (!validDraft(candidate)) throw new Error('Sai cấu trúc'); if (state.dirty && !window.confirm('Dữ liệu chưa lưu sẽ bị thay thế. Tiếp tục mở bản nháp?')) return; state.generation += 1; state.saveRequestId = null; state.data = candidate.data; state.result = null; state.recordId = null; state.version = null; state.dirty = true; clearErrors(); render(); setMessage('Đã mở bản nháp trên trang. Hãy tính lại trước khi in.'); } catch { setMessage('Không thể mở bản nháp: tệp không đúng định dạng CPC1.', 'error'); } }; reader.readAsText(file, 'utf-8'); }
  async function loadConfig() { const session = state.session; entryReady(false); try { const config = await window.CPC1_API.getConfig(); if (session !== state.session) return; if (!Array.isArray(config.locations) || !Array.isArray(config.forms)) throw new Error('Cấu hình thiếu danh sách biểu mẫu hoặc điểm lấy mẫu.'); state.config = config; state.location ||= locations()[0]?.id || null; $('formula-version').textContent = safeText(state.config.formula_version || 'Chưa công bố'); $('record-state').textContent = window.CPC1_API.capabilities?.persistence ? 'Sẵn sàng lưu Supabase' : 'Chế độ xem trước — chưa lưu'; $('connection-dot').className = 'dot online'; $('connection-text').textContent = 'Đã kết nối máy chủ'; entryReady(true); render(); } catch (error) { if (session !== state.session) return; $('connection-dot').className = 'dot offline'; $('connection-text').textContent = 'Không kết nối được máy chủ'; $('form-title').textContent = 'Không tải được cấu hình'; setMessage(`Không thể tải cấu hình: ${error.message}`, 'error'); } }
  async function openRequestedRecords() { if (!requestedRecords) return; if (window.CPC1_API.capabilities.auth && !state.session) { $('auth-dialog').showModal(); return; } requestedRecords = false; await listRecords(); }
  async function boot() { $('location-search').addEventListener('input', renderLocations); $('entry-form').addEventListener('submit', event => { event.preventDefault(); evaluate(); }); $('print').addEventListener('click', printPdf); $('record-save').addEventListener('click', saveRecord); $('record-load').addEventListener('click', listRecords); $('draft-download').addEventListener('click', downloadDraft); $('draft-open').addEventListener('click', () => $('draft-file').click()); $('draft-file').addEventListener('change', e => { openDraft(e.target.files[0]); e.target.value = ''; }); $('auth-close').addEventListener('click', () => $('auth-dialog').close()); $('records-close').addEventListener('click', () => $('records-dialog').close()); $('auth-form').addEventListener('submit', signIn); $('auth-button').addEventListener('click', async () => { if (state.session) { if (state.dirty && !window.confirm('Dữ liệu chưa lưu trên trang sẽ bị xóa khi đăng xuất. Tiếp tục?')) return; state.generation += 1; state.saveRequestId = null; state.session = null; try { await window.CPC1_API.signOut(); } catch (error) { setMessage(`Không thể xác nhận đăng xuất: ${error.message}`, 'error'); } state.config = null; state.location = null; state.data = blankData(); state.result = null; state.recordId = null; state.version = null; state.dirty = false; $('location-list').replaceChildren(); $('location-count').textContent = '0/0'; $('records-list').replaceChildren(); if ($('records-dialog').open) $('records-dialog').close(); $('auth-email').value = ''; $('auth-password').value = ''; $('auth-button').textContent = 'Đăng nhập'; $('record-state').textContent = 'Chưa đăng nhập'; welcome(); } else $('auth-dialog').showModal(); }); window.addEventListener('beforeunload', e => { if (state.dirty) { e.preventDefault(); e.returnValue = ''; } }); if (await refreshSession()) await loadConfig(); await openRequestedRecords(); }
  boot();
})();
