(() => {
  'use strict';
  const $=id=>document.getElementById(id), clone=x=>JSON.parse(JSON.stringify(x));
  const entryQuery=new URLSearchParams(location.search);
  let requestedRecords=entryQuery.get('view')==='records';
  let requestedForm=entryQuery.get('form');
  const S={system:new URLSearchParams(location.search).get('system')==='nitrogen'?'nitrogen':'air',config:null,active:null,point:null,data:null,result:null,recordId:null,version:null,dirty:false,generation:0,pending:0,session:null};
  const blank=()=>({system:S.system,meta:{},equipment:{},forms:{},controls:{positive_count:'',executed_by:'',result_date:''},trend:{}});
  const form=()=>S.config?.forms?.find(x=>x.id===S.active), get=(p,o=S.data)=>p.reduce((v,k)=>v&&typeof v==='object'?v[k]:undefined,o)??'', put=(p,v)=>{let o=S.data;p.slice(0,-1).forEach(k=>o=o[k]??={});o[p.at(-1)]=v};
  const tx=v=>typeof v==='string'?v:'', st=x=>({pass:'Đạt',fail:'Không đạt',incomplete:'Chưa đủ dữ liệu',invalid:'Dữ liệu không hợp lệ',pending:'Chưa có cấu hình SOP',not_configured:'Chưa cấu hình SOP'}[String(x||'').toLowerCase()]||'Chưa tính'), sc=x=>['pass','fail','incomplete','invalid','pending','not_configured'].includes(String(x).toLowerCase())?String(x).toLowerCase():'incomplete';
  const msg=(v,c='')=>{const n=$('message');n.textContent=v;n.className='message '+c};
  const el=(tag,a={},kids=[])=>{const n=document.createElement(tag);Object.entries(a).forEach(([k,v])=>{if(k==='className')n.className=v;else if(k==='text')n.textContent=v;else if(k.startsWith('on'))n.addEventListener(k.slice(2).toLowerCase(),v);else if(v!=null)n.setAttribute(k,v)});(Array.isArray(kids)?kids:[kids]).flat(Infinity).filter(Boolean).forEach(k=>n.append(k));return n};
  const changed=()=>{S.generation++;S.result=null;S.dirty=true;$('record-state').textContent=S.recordId?`Hồ sơ ${S.recordId} có thay đổi chưa lưu`:'Có thay đổi chưa lưu trên hệ thống';document.querySelectorAll('.result-row,.mini-status,.summary-row').forEach(x=>x.remove());const badge=$('form-status');if(badge){badge.textContent='Toàn biểu mẫu: Chưa tính';badge.className='status incomplete'};clearErrors()};
  function field(path,d){
    const id='gas-'+path.join('-').replace(/[^\w-]/g,'-'), wrap=el('div',{className:'field'}), label=el('label',{for:id,text:`${d.label}${d.unit?` (${d.unit})`:''}`}), input=d.type==='textarea'?el('textarea',{id,name:path.join('.'),rows:'3'}):el('input',{id,name:path.join('.'),type:d.type==='date'?'date':'text',inputmode:d.type==='number'?'decimal':null});
    input.setAttribute('aria-describedby',id+'-error');input.value=tx(get(path));input.addEventListener('input',()=>{put(path,input.value);changed()});wrap.append(label,input);if(d.help)wrap.append(el('small',{className:'help',text:d.help}));wrap.append(el('p',{id:id+'-error',className:'field-error'}));return wrap;
  }
  const card=(title,description,content)=>el('section',{className:'card'},[el('div',{className:'card-title'},[el('h3',{text:title}),description&&el('p',{className:'muted',text:description})]),content]);
  function entryReady(ready){['draft-download','draft-open','record-load','record-save','evaluate','print','point-search'].forEach(id=>$(id).disabled=!ready);document.querySelector('.actionbar').hidden=!ready;}
  function welcome(){entryReady(false);$('page-title').textContent=S.system==='air'?'Khí nén':'Khí nitơ';$('formula-version').textContent='Biểu mẫu và dữ liệu được bảo vệ bằng tài khoản riêng.';$('connection').textContent='Chưa đăng nhập';$('record-state').textContent='Chưa đăng nhập';$('form-title').textContent='Bắt đầu nhập báo cáo';$('form-kind').textContent='KHÔNG GIAN LÀM VIỆC';$('form-description').textContent='Đăng nhập để chọn biểu mẫu, nhập số liệu và mở hồ sơ đã lưu.';$('form-status').hidden=true;$('point-count').textContent='Các điểm lấy mẫu sẽ hiện sau khi đăng nhập.';$('form-body').replaceChildren(el('section',{className:'entry-welcome'},[el('h3',{text:'Nhập liệu rõ ràng. Lưu lại từng phiên bản.'}),el('p',{text:'Nhập số liệu theo biểu mẫu → tính và đánh giá → lưu hồ sơ → in theo form gốc.'}),el('button',{type:'button',className:'primary',text:'Đăng nhập để bắt đầu',onClick:auth})]));msg('');}
  const point=()=>form()?.locations?.find(x=>x.id===S.point);
  function renderTabs(){const n=$('form-tabs');n.replaceChildren();(S.config?.forms||[]).forEach(f=>{const r=S.result?.forms?.[f.id],b=el('button',{type:'button',className:'tab '+(f.id===S.active?'selected':''),'aria-current':f.id===S.active?'page':null,text:f.id.toUpperCase(),onClick:()=>switchForm(f.id)});if(r?.status)b.append(el('span',{className:'mini-status '+sc(r.status),text:st(r.status)}));n.append(b)})}
  function renderPoints(){const n=$('point-list'),q=$('point-search').value.trim().toLocaleLowerCase('vi'),all=form()?.locations||[],items=all.filter(x=>!q||`${x.id} ${x.name}`.toLocaleLowerCase('vi').includes(q));n.replaceChildren();$('point-count').textContent=form()?.kind==='measurement'?`${items.length}/${all.length} điểm`:'Biểu mẫu không có điểm lấy mẫu';items.forEach(p=>{const r=S.result?.forms?.[S.active]?.rows?.[p.id],b=el('button',{type:'button',role:'option','aria-selected':p.id===S.point?'true':'false',className:'point '+(p.id===S.point?'selected':''),onClick:()=>{S.point=p.id;render()}},[el('strong',{text:p.id}),el('span',{text:p.name}),p.grade&&el('small',{text:'Cấp '+p.grade}),r?.status&&el('span',{className:'mini-status '+sc(r.status),text:st(r.status)})]);n.append(b)})}
  const valueLabel=k=>({flow:'Lưu lượng (mL/phút)',reading:'Giá trị đọc trên tuýp (mg/m³)',duration:'Thời gian lấy mẫu (phút)',p05:'Tiểu phân ≥ 0,5 µm',p5:'Tiểu phân ≥ 5,0 µm',dewpoint:'Điểm sương',oil:'Vết dầu',microbial:'Vi sinh vật',purity:'Độ tinh khiết',positive_count:'Chứng dương',result:'Kết quả tính',raw_result:'Giá trị gốc',print_result:'Giá trị in'}[k]||k);
  const limitLabel=(k,v)=>({p05:`Tiểu phân ≥ 0,5 µm ≤ ${v} hạt/m³`,p5:`Tiểu phân ≥ 5,0 µm ≤ ${v} hạt/m³`,dewpoint:`Điểm sương ≤ ${v} °C`,oil:`Vết dầu ≤ ${v} mg/m³`,microbial:`Vi sinh vật ≤ ${v} CFU/m³`,purity:`Độ tinh khiết nitơ ≥ ${v}%`}[k]||`${k}: ${v}`);
  function controls(){const c=S.config.controls_fields||[],media=['media_batch','media_expiry'].map(k=>S.config.meta_fields?.find(x=>x.key===k)).filter(Boolean),r=S.result?.controls;return card('Chứng dương và môi trường','Máy chủ đánh giá chứng dương; không tự điền kết quả.',[el('div',{className:'field-grid'},[...c.map(d=>field(['controls',d.key],d)),...media.map(d=>field(['meta',d.key],d))]),r&&el('div',{className:'result-row '+sc(r.status)},[el('strong',{text:`Chứng dương: ${st(r.status)}`}),...Object.entries(r.values||{}).filter(([k])=>k!=='raw_result').map(([k,v])=>el('span',{text:`${valueLabel(k)}: ${v}`})),...Object.values(r.errors||{}).map(v=>el('p',{className:'field-error',text:String(v)}))])])}
  function rowResult(){const r=S.result?.forms?.[S.active]?.rows?.[S.point];if(!r)return null;const values=Object.entries(r.values||{}).filter(([k])=>k!=='raw_result').map(([k,v])=>`${valueLabel(k)}: ${v}`).join(' · ');return el('div',{className:'result-row '+sc(r.status)},[el('strong',{text:'Điểm đang chọn: '+st(r.status)}),values&&el('span',{text:values}),...Object.values(r.errors||{}).map(v=>el('p',{className:'field-error',text:String(v)}))])}
  function measurement(){
    const f=form(),p=point();if(!p)return el('p',{className:'empty',text:'Chưa chọn được điểm lấy mẫu.'});
    const fields=el('div',{className:'field-grid'},f.fields.map(d=>field(['forms',f.id,p.id,d.key],d)));
    const equip=f.equipment_fields?.length ? card('Thiết bị đo','Thông tin dụng cụ áp dụng cho biểu mẫu này.',el('div',{className:'field-grid'},f.equipment_fields.map(d=>field(['equipment',f.id,d.key],d)))) : null;
    const meta=(S.config.meta_fields||[]).filter(d=>d.form===f.id);
    return el('div',{},[el('p',{className:'point-heading',text:`${p.id} — ${p.name}`}),p.limits&&Object.keys(p.limits).length&&el('p',{className:'limits',text:'Giới hạn tại điểm: '+Object.entries(p.limits).map(([k,v])=>limitLabel(k,v)).join(' · ')}),card('Số liệu đo','Nhập đúng đơn vị. Số thập phân dùng dấu phẩy hoặc dấu chấm; không dùng dấu phân cách hàng nghìn.',fields),equip,f.id==='bm04'&&controls(),meta.length&&card('Nhận xét biểu mẫu','',el('div',{className:'field-grid'},meta.map(d=>field(['meta',d.key],d)))),rowResult()].filter(Boolean));
  }
  function summary(){const f=form(),rows=(S.config.forms||[]).filter(x=>x.kind==='measurement').map(x=>{const r=S.result?.forms?.[x.id],q=r?.summary;return el('div',{className:'summary-row'},[el('strong',{text:`${x.id.toUpperCase()} — ${x.title}`}),el('span',{className:'status '+sc(r?.status),text:st(r?.status)}),el('span',{text:q?`${q.pass??0} đạt · ${q.fail??0} không đạt · ${q.incomplete??0} chưa đủ / ${q.total??0} điểm`:'Chưa có đánh giá từ máy chủ'})])});const control=S.result?.controls||S.result?.summary?.controls,meta=(S.config.meta_fields||[]).filter(x=>x.form===f.id);return el('div',{},[card('Tổng hợp chất lượng','Các số liệu và trạng thái do máy chủ trả về.',[...rows,control&&el('div',{className:'summary-row'},[el('strong',{text:'BM04 — Chứng dương'}),el('span',{className:'status '+sc(control.status),text:st(control.status)}),el('span',{text:Object.entries(control.values||{}).map(([k,v])=>`${valueLabel(k)}: ${v}`).join(' · ')||'Chưa có kết quả chứng dương'})])]),meta.length&&card('Nhận xét biểu mẫu','',el('div',{className:'field-grid'},meta.map(d=>field(['meta',d.key],d))))].filter(Boolean))}
  function trend(){return el('div',{},[el('div',{className:'notice',text:'Chưa cấu hình SOP cho phép tự tính giới hạn cảnh báo/hành động. Chỉ nhập nội dung phân tích; máy chủ không tự quyết định giới hạn.'}),card('Nội dung phân tích xu hướng','',el('div',{className:'field-grid'},(S.config.trend_fields||[]).map(d=>field(['trend',d.key],d))))])}
  function general(){const fs=(S.config.meta_fields||[]).filter(d=>!d.form&&!['media_batch','media_expiry'].includes(d.key));return fs.length&&card('Thông tin báo cáo','',el('div',{className:'field-grid'},fs.map(d=>field(['meta',d.key],d))))}
  function assumptions(){const a=S.config.assumptions;if(!a?.length)return null;return el('details',{className:'assumptions'},[el('summary',{text:'Giả định/điểm cần QA xác nhận từ cấu hình nguồn'}),el('ul',{},a.map(x=>el('li',{text:typeof x==='string'?x:JSON.stringify(x)})))])}
  function renderBody(){const f=form();if(!f)return;$('form-kind').textContent=f.kind==='measurement'?'Nhập kết quả tại điểm':f.kind==='summary'?'Tổng hợp máy chủ':'Phân tích xu hướng';$('form-title').textContent=`${f.id.toUpperCase()} · ${f.title}`;$('form-description').textContent=f.kind==='measurement'?'Chọn điểm ở cột bên trái, nhập ô trống rồi gửi máy chủ đánh giá.':f.kind==='summary'?'Kết luận được tổng hợp từ các chỉ tiêu đã nhập.':'Nhập nội dung phân tích để in theo biểu mẫu.';const r=S.result?.forms?.[f.id],badge=$('form-status');badge.textContent='Toàn biểu mẫu: '+st(r?.status);badge.className='status '+sc(r?.status);$('form-body').replaceChildren(...[f.kind==='measurement'?measurement():f.kind==='summary'?summary():trend(),general(),assumptions()].filter(Boolean))}
  function render(){renderTabs();renderPoints();renderBody();document.querySelectorAll('.system-choice').forEach(b=>b.setAttribute('aria-pressed',String(b.id===S.system)))}
  function switchForm(id){const f=S.config.forms.find(x=>x.id===id);S.active=id;S.point=f.locations?.some(x=>x.id===S.point)?S.point:f.locations?.[0]?.id||null;render()}
  function clearErrors(){$('error-summary').hidden=true;$('error-summary').replaceChildren();document.querySelectorAll('[aria-invalid="true"]').forEach(x=>x.removeAttribute('aria-invalid'));document.querySelectorAll('.field-error').forEach(x=>{if(x.id)x.textContent=''})}
  function errors(result){clearErrors();const e=[],row=result?.forms?.[S.active]?.rows?.[S.point];Object.entries(row?.errors||{}).forEach(([k,v])=>e.push([['forms',S.active,S.point,k],v]));Object.entries(result?.controls?.errors||{}).forEach(([k,v])=>e.push([['controls',k],v]));if(!e.length)return;const list=el('ul');e.forEach(([p,v])=>{const input=document.querySelector(`[name="${CSS.escape(p.join('.'))}"]`);if(input){input.setAttribute('aria-invalid','true');const b=$(input.id+'-error');if(b)b.textContent=String(v);list.append(el('li',{},el('a',{href:'#'+input.id,text:String(v),onClick:()=>input.focus()})))}});if(list.children.length){const box=$('error-summary');box.append(el('h2',{text:'Cần kiểm tra lại dữ liệu'}),list);box.hidden=false;box.focus()}}
  async function config(keep=null){const token=++S.pending,system=S.system,session=S.session;S.generation++;S.config=null;S.result=null;entryReady(false);render();if(GasAPI.capabilities.auth&&!S.session){welcome();return}msg('');$('form-status').hidden=false;$('form-body').replaceChildren(el('p',{className:'empty',text:'Đang tải biểu mẫu…'}));$('connection').textContent='Đang tải cấu hình…';try{const c=await GasAPI.getGasConfig(system);if(token!==S.pending||system!==S.system||session!==S.session)return;if(!Array.isArray(c.forms))throw Error('Cấu hình không có danh sách biểu mẫu.');S.config=c;S.data=keep||blank();const selected=c.forms.find(f=>f.id===requestedForm)||c.forms[0];S.active=selected?.id||null;S.point=selected?.locations?.[0]?.id||null;requestedForm=null;$('page-title').textContent=c.title||(system==='air'?'Khí nén':'Nitơ');$('formula-version').textContent='Công thức: '+(c.formula_version||'chưa công bố');$('connection').textContent=GasAPI.mode==='cloud'?'Đã kết nối dịch vụ hồ sơ':'Chế độ xem trước · chưa lưu Supabase';$('record-state').textContent=GasAPI.mode==='cloud'?'Sẵn sàng lưu Supabase':'Chưa lưu trên hệ thống';msg('');entryReady(true);render()}catch(e){if(token===S.pending&&session===S.session){$('connection').textContent='Không tải được cấu hình';msg('Không thể tải cấu hình: '+e.message,'error')}}}
  async function evaluate(e){e.preventDefault();if(!S.config)return;const g=S.generation,data=clone(S.data);$('evaluate').disabled=true;msg('Đang gửi số liệu để máy chủ tính và đánh giá…');try{const r=await GasAPI.evaluate(data);if(g!==S.generation||data.system!==S.system){msg('Dữ liệu đã thay đổi trong khi tính; kết quả cũ không được áp dụng.','error');return}S.result=r;msg('Máy chủ đã trả kết quả. Sửa bất kỳ ô nào sẽ cần tính lại.');render();errors(r)}catch(x){msg('Không thể tính: '+x.message+'. Dữ liệu đang nhập vẫn được giữ.','error')}finally{$('evaluate').disabled=false}}
  async function print(){if(!S.config)return;const w=window.open('','_blank');if(w)w.opener=null;const g=S.generation,data=clone(S.data);$('print').disabled=true;msg('Đang tạo PDF theo biểu mẫu gốc…');try{const b=await GasAPI.report(S.active,data);if(g!==S.generation||data.system!==S.system){w?.close();msg('Dữ liệu đã thay đổi; không mở PDF tạo từ bản cũ.','error');return}if(!b.type.includes('pdf'))throw Error('Máy chủ không trả về PDF.');const u=URL.createObjectURL(b);setTimeout(()=>URL.revokeObjectURL(u),60000);if(w){w.location.href=u;msg('Đã mở PDF. Khi in chọn Kích thước thực / 100%.')}else{$('message').append(' Popup bị chặn; ',el('a',{href:u,download:`CPC1-${S.system}-${S.active}.pdf`,text:'Tải PDF bản nháp'}))}}catch(e){w?.close();msg('Không thể tạo PDF: '+e.message,'error')}finally{$('print').disabled=false}}
  function exportDraft(){const u=URL.createObjectURL(new Blob([JSON.stringify({version:1,data:clone(S.data)},null,2)],{type:'application/json'})),a=el('a',{href:u,download:`cpc1-${S.system}-ban-nhap.json`});document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),0);msg('Đã tải bản nháp JSON về máy; dữ liệu không được giữ trong trình duyệt.')}
  function valid(d){const x=d?.data;return d?.version===1&&x&&typeof x==='object'&&!Array.isArray(x)&&['air','nitrogen'].includes(x.system)&&['meta','equipment','forms','controls','trend'].every(k=>x[k]&&typeof x[k]==='object'&&!Array.isArray(x[k]))}
  function importDraft(file){if(!file||file.size>1048576)return msg('Chỉ mở bản nháp JSON dưới 1 MB.','error');const r=new FileReader();r.onload=()=>{try{const d=JSON.parse(String(r.result));if(!valid(d))throw Error();if(S.dirty&&!confirm('Dữ liệu chưa lưu sẽ bị thay thế. Tiếp tục?'))return;S.generation++;S.system=d.data.system;S.data=clone(d.data);S.result=null;S.recordId=null;S.version=null;S.dirty=true;config(S.data);msg('Đã mở bản nháp. Hãy tính lại trước khi in hoặc lưu.')}catch{msg('Không thể mở bản nháp: tệp không đúng định dạng CPC1.','error')}};r.readAsText(file,'utf-8')}
  async function save(){if(!GasAPI.capabilities.persistence)return msg('Supabase chưa được kết nối cho môi trường này.','error');const g=S.generation,data=clone(S.data);$('record-save').disabled=true;try{const r=await GasAPI.save(data,{recordId:S.recordId,expectedVersion:S.version,title:`${S.config.title} — báo cáo nháp`});if(g!==S.generation||data.system!==S.system)return msg('Đã có thay đổi mới hơn; không ghi đè trạng thái nháp hiện tại.','error');S.recordId=r.id;S.version=r.version;S.dirty=false;$('record-state').textContent=`Đã lưu Supabase · hồ sơ ${r.id} · phiên bản ${r.version}`;msg('Đã lưu hồ sơ Supabase.')}catch(e){msg('Không thể lưu: '+e.message+'. Dữ liệu đang nhập vẫn được giữ.','error')}finally{$('record-save').disabled=false}}
  async function list(){if(!GasAPI.capabilities.persistence)return msg('Supabase chưa được kết nối cho môi trường này.','error');const d=$('records-dialog'),n=$('records-list'),session=S.session;d.showModal();n.replaceChildren(el('p',{text:'Đang tải hồ sơ…'}));try{const rs=await GasAPI.list(S.system);if(session!==S.session)return;const gas=rs.filter(r=>r.system===S.system);n.replaceChildren(...(gas.length?gas.map(r=>el('button',{type:'button',className:'saved-record',onClick:()=>{d.close();load(r.id)}},[el('strong',{text:r.title||`Hồ sơ ${r.id}`}),el('span',{text:`${r.updated_at||''} · phiên bản ${r.version??'—'}`})])):[el('p',{text:'Chưa có hồ sơ đã lưu cho hệ thống này.'})]))}catch(e){if(session===S.session)n.replaceChildren(el('p',{className:'field-error',text:'Không tải được danh sách: '+e.message}))}}
  async function load(id){if(S.dirty&&!confirm('Dữ liệu chưa lưu sẽ bị thay thế. Tiếp tục?'))return;const g=S.generation,session=S.session;try{const r=await GasAPI.load(id);if(g!==S.generation||session!==S.session||r?.data?.system!==S.system)return;if(!r?.data)throw Error('Hồ sơ không có dữ liệu.');S.data=clone(r.data);S.result=r.evaluation||r.result||null;S.recordId=r.id;S.version=r.version;S.dirty=false;S.generation++;$('record-state').textContent=`Đã mở Supabase · hồ sơ ${r.id} · phiên bản ${r.version}`;render();msg('Đã mở hồ sơ từ Supabase.')}catch(e){msg('Không thể mở hồ sơ: '+e.message,'error')}}
  async function session(){$('auth-button').hidden=!GasAPI.capabilities.auth;S.session=await GasAPI.getSession();$('auth-button').textContent=S.session?'Đăng xuất':'Đăng nhập'}
  async function auth(){if(S.session){if(S.dirty&&!confirm('Dữ liệu chưa lưu trên trang sẽ bị xóa khi đăng xuất. Tiếp tục?'))return;S.generation++;S.pending++;S.session=null;try{await GasAPI.signOut()}catch(e){msg('Không thể xác nhận đăng xuất: '+e.message,'error')}S.recordId=null;S.version=null;S.result=null;S.dirty=false;S.data=blank();$('record-state').textContent='Đã đăng xuất · dữ liệu nháp trên trang đã xóa';S.config=null;render();await session();return config()}$('auth-dialog').showModal()}
  async function signIn(e){e.preventDefault();try{await GasAPI.signIn($('auth-email').value,$('auth-password').value);$('auth-password').value='';$('auth-dialog').close();await session();if(!S.config)await config();if(S.config){msg('Đã đăng nhập.');await openRequestedRecords()}}catch(x){$('auth-error').textContent='Không thể đăng nhập: '+x.message}}
  function system(x){if(x===S.system)return;if(S.dirty&&!confirm('Dữ liệu chưa lưu sẽ bị thay thế khi đổi hệ thống. Tiếp tục?'))return;S.system=x;S.generation++;S.data=blank();S.result=null;S.recordId=null;S.version=null;S.dirty=false;config()}
  async function openRequestedRecords(){if(!requestedRecords)return;if(GasAPI.capabilities.auth&&!S.session){$('auth-dialog').showModal();return}requestedRecords=false;await list()}
  async function boot(){$('entry-form').addEventListener('submit',evaluate);$('print').addEventListener('click',print);$('draft-download').addEventListener('click',exportDraft);$('draft-open').addEventListener('click',()=>$('draft-file').click());$('draft-file').addEventListener('change',e=>{importDraft(e.target.files[0]);e.target.value=''});$('record-save').addEventListener('click',save);$('record-load').addEventListener('click',list);$('records-close').addEventListener('click',()=>$('records-dialog').close());$('auth-button').addEventListener('click',auth);$('auth-close').addEventListener('click',()=>$('auth-dialog').close());$('auth-form').addEventListener('submit',signIn);$('air').addEventListener('click',()=>system('air'));$('nitrogen').addEventListener('click',()=>system('nitrogen'));$('point-search').addEventListener('input',renderPoints);addEventListener('beforeunload',e=>{if(S.dirty){e.preventDefault();e.returnValue=''}});try{await session();await config();await openRequestedRecords()}catch(e){$('connection').textContent='Không xác minh được phiên đăng nhập';msg('Không thể khởi động dịch vụ: '+e.message+' Hãy thử đăng nhập lại.','error')}}
  boot();
})();
